#!/usr/bin/perl
#
# Copyright (C) 2003-2014 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

use constant;
# Only use when debugging because it can lead to 50% performance loss
# use diagnostics;
use integer;
use sigtrap  qw(SEGV BUS);
use strict   qw(subs vars refs);
use subs     qw(afunc blurfl);
use warnings qw(all);
use sort     qw(stable _quicksort _mergesort);

my $table;
$| = 1;

my ($db, $type) = ('', '');

while (<>) {
    $db = $1 if /^USE (.*);$/;
    $db = $1 if /^-- Host: .+?    Database: (.+)$/;

    # Skip 'mysql' database
    next if $db eq '`mysql`';

    if (/^CREATE TABLE `(.*)` \(/) {
	$table = $1;
    }

    if (/^\) (ENGINE|TYPE)=([a-zA-Z]*).*;$/) {
	$type = $2;
	next if $type ne 'MyISAM';
	    
	print "ALTER TABLE $db.`$table` TYPE = InnoDB;\n";
    }
}
